version: '3'

services:
  web:
    build: ./docker/web
    restart: always
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER:#1000
      - APACHE_RUN_GROUP:#1000
    volumes:
      - .:/var/www/html/
      - ./docker/web/apache2.conf:/etc/apache2/apache2.conf
      - ./docker/web/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: quinta
    ports:
      - 33060:3306
